
    @extends('layouts.master')

    @section('content')
    <section class="section-padding">
    <div class="container">
        <div class="row col-lg-12" style="margin-top:70px;">
       
                <div class="col-lg-8 col-lg-offset-2">
                    <center>
                        <h2>About Us</h2>
                        <hr class="bottom-line">
                    </center>
                        <p class="subtitle">Cebu City Pound promotes pet adoption by finding suitable homes for those animals surrendered by their owners, abandoned and neglected pets who lived inside Cebu City. The pound uses Facebook page where they post and promotes animals to find suitable owners by posting their photos together with its description of what breed and other information regarding to that animal. Administrators of the Cebu City Pound replies to comments and private messages from clients, but it takes time and also a hassle for the Admin replying to a series of questions that contains the same answer. This system also aims to organize their means of communication.  Upon registration, the administrator from Cebu Pound gives questions to clients to see if they are qualified to take care of the animal. If qualified Cebu City Pound will then manually process the papers of the animal.<br><br>

                        Online Animal Management System is a web-based application with a touch of mobile by which it will promote homeless animals in finding their new home. Clients are able to see photos with descriptions of those animals without shelters, finds their match based on the information that the Clients inserted upon Client's registration. In addition, if the client is qualified by the system they’ll have to fill out a printable form generated by the system in which the Cebu City Pound are the only ones who are able to print because there are fees that needs to be paid, same goes for impounding. Once the client is registered as the owner of a particular animal, the client will then get notified via mobile application according to their pet’s schedule for vaccination or any animal concerns. It will then help the veterinary department to have a convenient way of processing  their records and less hassle  for them to check each record for every animal. Both the administrator and clients can view the animal’s history through the web and mobile application.</p><br>

                        <center><h4>OAMS' Developers</h4></center>
                        <br><br><br>
                        <div class="row">
                            <div class="col-md-3">
                                    <div class="team boxed-grey">
                                        <div class="inner">
                                            <div class="avatar"><img src="img/sham.jpg" alt="" class="img-responsive img-circle" />
                                            <center>
                                            <h5>Shamesse Delda</h5>
                                            <p class="subtitle">Web Developer</p>
                                            </center>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="col-md-3">
                                    <div class="team boxed-grey">
                                        <div class="inner">
                                            <div class="avatar"><img src="img/diz.jpg" alt="" class="img-responsive img-circle" />
                                            <center>
                                            <h5>Diza Maitem</h5>
                                            <p class="subtitle">Web Developer</p>
                                            </center>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="col-md-3">
                                    <div class="team boxed-grey">
                                        <div class="inner">
                                            <div class="avatar"><img src="img/jen.jpg" alt="" class="img-responsive img-circle" />
                                            <center>
                                            <h5>Jenny Placer</h5>
                                            <p class="subtitle">Android Developer</p>
                                            </center>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="col-md-3">
                                    <div class="team boxed-grey">
                                        <div class="inner">
                                            <div class="avatar"><img src="img/rey.jpg" alt="" class="img-responsive img-circle" />
                                            <center>
                                            <h5>Rey Abellana</h5>
                                            <p class="subtitle">Documentation</p>
                                            </center>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div> 
                </div> 
        </div>  
    </div>
    @endsection
